const upbitCoinPrice = {};
const upbitPriceRate = {};

const ws = new WebSocket("wss://api.upbit.com/websocket/v1");
ws.binaryType = "arraybuffer";

ws.onopen = (e) => {
  ws.send(
    JSON.stringify([
      { ticket: "kimp" },
      {
        type: "ticker",
        codes: [
          "KRW-BTC",
          "KRW-ETH",
          "KRW-NEO",
          "KRW-MTL",
          "KRW-LTC",
          "KRW-XRP",
          "KRW-ETC",
          "KRW-OMG",
          "KRW-SNT",
          "KRW-WAVES",
          "KRW-XEM",
          "KRW-QTUM",
          "KRW-LSK",
          "KRW-STEEM",
          "KRW-XLM",
          "KRW-ARDR",
          "KRW-KMD",
          "KRW-ARK",
          "KRW-STORJ",
          "KRW-GRS",
          "KRW-REP",
          "KRW-EMC2",
          "KRW-ADA",
          "KRW-SBD",
          "KRW-POWR",
          "KRW-BTG",
          "KRW-ICX",
          "KRW-EOS",
          "KRW-TRX",
          "KRW-SC",
          "KRW-IGNIS",
          "KRW-ONT",
          "KRW-ZIL",
          "KRW-POLY",
          "KRW-ZRX",
          "KRW-LOOM",
          "KRW-BCH",
          "KRW-ADX",
          "KRW-BAT",
          "KRW-IOST",
          "KRW-DMT",
          "KRW-RFR",
          "KRW-CVC",
          "KRW-IQ",
          "KRW-IOTA",
          "KRW-MFT",
          "KRW-ONG",
          "KRW-GAS",
          "KRW-UPP",
          "KRW-ELF",
          "KRW-KNC",
          "KRW-BSV",
          "KRW-THETA",
          "KRW-EDR",
          "KRW-QKC",
          "KRW-BTT",
          "KRW-MOC",
          "KRW-ENJ",
          "KRW-TFUEL",
          "KRW-MANA",
          "KRW-ANKR",
          "KRW-AERGO",
          "KRW-ATOM",
          "KRW-TT",
          "KRW-CRE",
          "KRW-SOLVE",
          "KRW-MBL",
          "KRW-TSHP",
          "KRW-WAXP",
          "KRW-HBAR",
          "KRW-MED",
          "KRW-MLK",
          "KRW-STPT",
          "KRW-ORBS",
          "KRW-VET",
          "KRW-CHZ",
          "KRW-PXL",
          "KRW-STMX",
          "KRW-DKA",
          "KRW-HIVE",
          "KRW-KAVA",
          "KRW-AHT",
          "KRW-LINK",
          "KRW-XTZ",
          "KRW-BORA",
          "KRW-JST",
          "KRW-CRO",
          "KRW-TON",
          "KRW-SXP",
          "KRW-LAMB",
          "KRW-HUNT",
          "KRW-MARO",
          "KRW-PLA",
          "KRW-DOT",
          "KRW-SRM",
          "KRW-MVL",
          "KRW-PCI",
          "KRW-STRAX",
          "KRW-AQT",
          "KRW-BCHA",
          "KRW-GLM",
          "KRW-QTCON",
          "KRW-SSX",
          "KRW-META",
          "KRW-OBSR",
          "KRW-FCT2",
          "KRW-LBC",
          "KRW-CBK",
          "KRW-SAND",
          "KRW-HUM",
          "KRW-DOGE",
          "KRW-STRK",
          "KRW-PUNDIX",
          "KRW-FLOW",
          "KRW-DAWN",
          "KRW-AXS",
          "KRW-STX",
        ],
      },
      { format: "SIMPLE" },
    ])
  );
};

ws.onmessage = (e) => {
  const a = new TextDecoder("utf-8");
  const b = new Uint8Array(e.data);
  const c = JSON.parse(a.decode(b));
  // 현재가 등락률 52고 52저

  // console.log(c);
  upbitCoinPrice[c.cd] = [c.tp, c.scr, c.h52wp, c.l52wp];
};

ws.onerror = (e) => console.log(e);

export default upbitCoinPrice;
